spring.datasource.url=jdbc:mysql://localhost:3306/spring_DB?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
server.servlet.context-path=/voiture
spring.main.allow-circular-references=true
spring.mail.default-encoding=UTF-8
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=AdamBahroun54@gmail.com
spring.mail.password=vzri ssee jfzm bqjn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.security.oauth2.client.registration.github.client-id=Ov23litorBjrx3NQNzwb
spring.security.oauth2.client.registration.github.client-secret=3dc60dc4758255f1bf0c884bf3230f9e1ee26c3b